### ISSUE TITLE
"I couldn't find any Diamond Ore blocks within 256."

### ISSUE THREAD

**Issue by moom0o** [Darthfett/mineflayer-blockfinder#19]
There is clearly diamond ore like 60 blocks underground.
It doesn't work.

I'm using the example

      point: bot.entity.position,
      matching: 56,
      maxDistance: 256,
      count: 1,

**Comment by rom1504** [comment]
Are you sure 56 is the right id ? There are several diamond types

**Comment by moom0o** [comment]
yes, diamond ore
![image](https://user-images.githubusercontent.com/48740106/64067076-4911be80-cbf0-11e9-8de9-3be709795cab.png)

**Comment by rom1504** [comment]
Ok you got the wrong id then. Use node-minecraft-data to get the right one
for your version

**Comment by moom0o** [comment]
![image](https://user-images.githubusercontent.com/48740106/64068642-d5c87680-cc08-11e9-9cbc-2a195afdbab3.png)
It says its the right id.

**Comment by rom1504** [comment]
How did you display this exactly ?
What version of minecraft are you using?

**Comment by TomHGsc** [comment]
I know this thread was closed.... But i'm experiencing the same issue.

I've set the ID to bedrock (7)... but for some reason it seems like it can never find anything. No bedrock, no grassblocks, nothing.
What was the fix @moom0o that eventually helped you out? Or anyone else knows what is going on?

`const mineflayer = require('mineflayer')
var blockFinderPlugin = require('mineflayer-blockfinder')(mineflayer);
const fs = require('fs')

function createBot () {
  const bot = mineflayer.createBot({
    host: '192.168.137.1',
    port: 25565,
    username: 'MAIL',
    password: 'PASSWORD',
    auth: 'microsoft'
  })
  bot.loadPlugin(blockFinderPlugin);
  //
  // blockFinderPlugin(bot);

  bot.on('spawn', () => {
    bot.findBlock({
      point: bot.entity.position,
      matching: 7, //90 = portal, 49 = obsidian, 1 = stone, 7 = bedrock
      maxDistance: 256,
      count: 1,
    }, function(err, blocks) {
      console.log(blocks)
    })
  })

  bot.on('spawn', function() {
    console.log("[BOT] - Spawned")
  bot.findBlock({
    point: bot.entity.position,
    matching: 7, //90 = portal, 49 = obsidian, 1 = stone, 7 = bedrock
    maxDistance: 16,
    count: 1,
  }, function(err, blocks) {
    console.log("[BOT] - findBLocks function started")
    if (err) {
      bot.chat('Error trying to find Bedrock: ' + err);
      setTimeout(kill, 5100)
    }
    console.log(blocks)
    if (blocks.length) {
      return bot.chat('I found a Bedrock block at ' + blocks[0].position + '.');
    } else {
      bot.chat("I couldn't find any Bedrock within 256.");
      setTimeout(kill, 5100)
    }
  });
  });

  bot.on('error', (err) => {
    console.log(err)
    process.exit(1)
  })

  // setInterval(kill, 5100)
  function kill () {
    bot.chat("/kill")
  }
}

createBot()
`

**Comment by moom0o** [comment]
> I know this thread was closed.... But i'm experiencing the same issue.
> 
> I've set the ID to bedrock (7)... but for some reason it seems like it can never find anything. No bedrock, no grassblocks, nothing. What was the fix @moom0o that eventually helped you out? Or anyone else knows what is going on?
> 
> ```
> const mineflayer = require('mineflayer')
> var blockFinderPlugin = require('mineflayer-blockfinder')(mineflayer);
> const fs = require('fs')
> 
> function createBot () {
>   const bot = mineflayer.createBot({
>     host: '192.168.137.1',
>     port: 25565,
>     username: 'MAIL',
>     password: 'PASSWORD',
>     auth: 'microsoft'
>   })
>   bot.loadPlugin(blockFinderPlugin);
>   //
>   // blockFinderPlugin(bot);
> 
>   bot.on('spawn', function() {
>     console.log("[BOT] - Spawned")
>   bot.findBlock({
>     point: bot.entity.position,
>     matching: 7, //90 = portal, 49 = obsidian, 1 = stone, 7 = bedrock
>     maxDistance: 16,
>     count: 1,
>   }, function(err, blocks) {
>     console.log("[BOT] - findBLocks function started")
>     if (err) {
>       bot.chat('Error trying to find Bedrock: ' + err);
>       setTimeout(kill, 5100)
>     }
>     console.log(blocks)
>     if (blocks.length) {
>       return bot.chat('I found a Bedrock block at ' + blocks[0].position + '.');
>     } else {
>       bot.chat("I couldn't find any Bedrock within 256.");
>       setTimeout(kill, 5100)
>     }
>   });
>   });
> 
>   bot.on('error', (err) => {
>     console.log(err)
>     process.exit(1)
>   })
> 
>   // setInterval(kill, 5100)
>   function kill () {
>     bot.chat("/kill")
>   }
> }
> 
> createBot()
> ```

Use https://github.com/PrismarineJS/mineflayer-pathfinder it's newer and updated.
