### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rom1504** [Darthfett/mineflayer-blockfinder#4]
I don't know what changed but I'm getting this running https://github.com/Darthfett/mineflayer-blockfinder/blob/master/examples/diamondFinder.js now (with the last commit from mineflayer)

(I noticed this because I'm using this plugin in https://github.com/rom1504/rbot)

**Comment by rom1504** [comment]
I'm getting this for dirt (id 3) too, so I think it's not a problem with the distance of the block.

**Comment by Darthfett** [comment]
Will need to get a local environment set up to test this with the latest mineflayer.

**Comment by rom1504** [comment]
I did test it with the latest mineflayer. #5 does solve this problem ;)
