### ISSUE TITLE
Node Package Not Up To Date

### ISSUE THREAD

**Issue by Tommsy64** [Darthfett/mineflayer-blockfinder#7]
If I specify mineflayer-blockfinder 0.0.5 in my package.json and run npm install, the saved files are not the latest version. (MAX_CPU_SPIN = 100, not 10)

I have to manually link this repository's latest commit to get the correct version.

**Comment by rom1504** [comment]
agreed a new version should be published

**Comment by simonmeusel** [comment]
Yes please

**Comment by simonmeusel** [comment]
@Darthfett
Just run
> npm version patch
> npm publish

**Comment by Darthfett** [comment]
Published 0.0.6, after updating a few things.

**Comment by Darthfett** [comment]
Thanks @simonmeusel for nudging me :)  Apologies to everyone for the non-responsiveness!
