### ISSUE TITLE
Count Option is Broken

### ISSUE THREAD

**Issue by Tommsy64** [Darthfett/mineflayer-blockfinder#8]
Many blocks found when the count > 1 are duplicates, although not _all_ of them.

Does this mean that the search algorithm is iterating over some blocks multiple times?

**Comment by Darthfett** [comment]
Don't know which version you're using, but an older version of the algorithm searches using the six faces of a cube, so edge blocks get hit twice, while corners get hit three times.  It also doesn't find the closest block first.

The newest algorithm should never search blocks twice, and should always return the closest blocks first.

I haven't been active on here, as mineflayer has often been dificult to install on my Windows laptop I use.  I would be happy to accept pull requests and add contributors if I know that things are at least being tested thoroughly.

**Comment by Darthfett** [comment]
Closing unless someone still sees this being broken -- I believe this was fixed in the past.
