### ISSUE TITLE
I can's find log block :(

### ISSUE THREAD

**Issue by camilleeyries** [Darthfett/mineflayer-blockfinder#9]
My script can't find any wood block with ID 17 or 4 ... Can you help me ?

**Comment by rom1504** [comment]
What did you try ?

**Comment by camilleeyries** [comment]
This: 
(idLib is lib of minecraft ID's... The lib say the log block's id is 17 or 4 but I can't found it)

function findBlocks(type, distance, point) {
 tmp = null;
 eval("var id = idLib." +  type + ".id");
 console.log("search for id: " + id);
bot.findBlock({
    point: point,
    matching: id,
	//matching: 4,
    maxDistance: distance,
    count: 1,
  }, function(err, blockPoints) {
    if (err) {
		console.log("ERROR: " + err);
		return;
		bot.quit('quitting');
    }
    if (blockPoints.length) {
		console.log("founded " + type + " with id " + id);
		tmp = blockPoints;
    } else {
		bot.chat("... I can't found... with distance = " + distance);
      return;
    }
  });
  if (tmp == null) {
	  console.log("I can't found any " + type + " with id " + id + ".");
	  return null;
  }
  else {
  console.log(tmp[0]);
}

  return bot.blockAt(tmp[0].position);
}

**Comment by camilleeyries** [comment]
euh... en fait vous êtes français alors je vois pas pourquoi je parle en anglais xD

**Comment by rom1504** [comment]
I think it's better if we keep talking in english so other people can understand ;)

You can't use mineflayer-blockfinder on its own, you have to use it along with mineflayer.

You should try the example there https://github.com/Darthfett/mineflayer-blockfinder#usage

Wood is 5 and 17 (see http://prismarinejs.github.io/minecraft-data/?d=blocks), you can use https://www.npmjs.com/package/minecraft-data if you want to automatically get the block id from the block name.

**Comment by camilleeyries** [comment]
Ok :) Thank you :)

**Comment by camilleeyries** [comment]
```javascript
var mcData = require("minecraft-data")("1.8.4");
var mineflayer = require('mineflayer');
var navigate = require('mineflayer-navigate')(mineflayer);
var findBlock = require('mineflayer-blockfinder')(mineflayer);
var scaffold = require('mineflayer-scaffold')(mineflayer);
var vec3 = mineflayer.vec3;
var chestBlock = null;
var chestPos = null;
var status = null;
var tmp;
var tmp2;
var blockChest = null;

if(process.argv.length<4 || process.argv.length>6)
{
    console.log("Usage : node WOODER.js <host> <port> [<name>] [<password>]");
    process.exit(1);
}

var bot = mineflayer.createBot({
    username: process.argv[4] ? process.argv[4] : "Timber",
    verbose: true,
    port:parseInt(process.argv[3]),
    host:process.argv[2],
    password:process.argv[5]
});

navigate(bot);
findBlock(bot);
scaffold(bot);

bot.on('spawn', function() {
	bot.chat('hello !! Define a chest with "!definechest". ');
	
});


	
bot.on('chat', function(username, message) {
	
	if (message == '!definechest') {
	        posChest = bot.players[username].entity.position;
	        blockChest = findBlocks('chest', 4, posChest);
			
			
			if (blockChest == null) {
				bot.chat("please redefine te chest...");
			}
			else 
			{
				console.log(blockChest);
		        bot.chat('Okay, i will store all the wood in the chest at ' + blockChest.position);
		
			}
	}
			
    if (message == '!come') {
        status == 'come';
		console.log("coming");
        bot.scaffold.to(bot.players[username].entity.position);
		console.log('status');
    }
	
	if (message == "!wood") {
		/*if (blockChest == null) {
			bot.chat("Please define a chest with !definechest");
			return;
		}*/
		var block = findBlocks("log", 50000, bot.entity.position);
		bot.scaffold.to(block.position, woodDiging);
	}
}
);

function woodDiging() {
	console.log("test");
}

function findBlocks(type, distance, point) {
 var id = mcData.blocksByName[type].id
	if (id == null) {
		console.log('No ID for block ' + type);
		
	}
 console.log("search for id: " + id);
bot.findBlock({
    point: point,
    matching: id,
    maxDistance: distance,
    count: 1,
  }, function(err, blockPoints) {
    if (err) {
		console.log("ERROR: " + err);
		return;
		bot.quit('quitting');
    }
    if (blockPoints.length) {
		console.log("founded " + type + " with id " + id);
		tmp = blockPoints;
    } else {
		bot.chat("... I can't found... with distance = " + distance);
      return;
    }
  });
  if (tmp == null) {
	  console.log("I can't found any " + type + " with id " + id + ".");
	  return null;
  }
  else {
  console.log(tmp[0]);
}

  return bot.blockAt(tmp[0].position);
}


function equip(toolName, destination) {
	function selectRod() {
		eval("var idLibObject = idLib." + toolName + ".id;");
	    var tool = bot.inventory.findInventoryItem(idLibObject);
	    var tool_count = bot.inventory.count(idLibObject);
	    if (tool) {
	        bot.equip(tool, 'hand');
	        console.log(tool_count + " fishing rods, " + tool.metadata + " damage taken from current " + toolName);
	    } else {
	        console.log('You do not have a ' + toolName + ' !');
	    }
	    return tool;
	}	
}
```

I have the same problem... The bot can't find log block... Can you help me ( again ) ?

**Comment by rom1504** [comment]
@camilleeyries I just tried it, and it works for me.
How far are the log blocks ?

**Comment by camilleeyries** [comment]
I am not at my home... I Will send a video soon.

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord

**Comment by Darthfett** [comment]
Working for rom, going to close since no response from user.
